In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[39, 1193, 9766, 134],
 [39, 1193, 9766, 2599],
 [39, 5918, 9766, 9105],
 [1054, 2529, 4002, 3853, 5477],
 [1054, 2529, 4002, 3853, 4615],
 [579, 39, 7874, 9766, 228],
 [6564, 2385, 6069, 3853]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
type(embedded_docs)

[[   0    0    0    0   39 1193 9766  134]
 [   0    0    0    0   39 1193 9766 2599]
 [   0    0    0    0   39 5918 9766 9105]
 [   0    0    0 1054 2529 4002 3853 5477]
 [   0    0    0 1054 2529 4002 3853 4615]
 [   0    0    0  579   39 7874 9766  228]
 [   0    0    0    0 6564 2385 6069 3853]]


numpy.ndarray

In [16]:
# feature repersentation
dim =10


In [19]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))

In [20]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0,   39, 1193, 9766,  134], dtype=int32)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([[[-4.56035510e-02,  3.62310894e-02,  1.65047757e-02,
         -4.07741293e-02, -1.73725113e-02, -3.36340889e-02,
          6.31865114e-03, -4.57605720e-02, -7.46206194e-03,
         -2.31056698e-02],
        [-4.56035510e-02,  3.62310894e-02,  1.65047757e-02,
         -4.07741293e-02, -1.73725113e-02, -3.36340889e-02,
          6.31865114e-03, -4.57605720e-02, -7.46206194e-03,
         -2.31056698e-02],
        [-4.56035510e-02,  3.62310894e-02,  1.65047757e-02,
         -4.07741293e-02, -1.73725113e-02, -3.36340889e-02,
          6.31865114e-03, -4.57605720e-02, -7.46206194e-03,
         -2.31056698e-02],
        [-4.56035510e-02,  3.62310894e-02,  1.65047757e-02,
         -4.07741293e-02, -1.73725113e-02, -3.36340889e-02,
          6.31865114e-03, -4.57605720e-02, -7.46206194e-03,
         -2.31056698e-02],
        [ 1.11374371e-02, -3.35425958e-02, -2.68444773e-02,
         -3.65614519e-02,  1.28342845e-02, -6.24197721e-03,
         -3.58075127e-02,  4.31591533e-02, -1.260901